name: Hello World Workflow

on:
  # push:
  #   branches: [ 'test' ]
  # pull_request:
  #   branches: [ test ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow'
        default: 'test'
        required: true

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
